import { NextRequest, NextResponse } from "next/server";
import dayjs from "dayjs";

function scoreColor(score: number) {
    if (score >= 75) return "#43d9ad";
    if (score >= 50) return "#f59e0b";
    return "#ef4444";
}
function scoreLabel(score: number) {
    if (score >= 85) return "Excellent";
    if (score >= 70) return "Good";
    if (score >= 50) return "Average";
    return "Needs Improvement";
}

export async function POST(req: NextRequest) {
    try {
        const { interview, userName } = await req.json();
        const { feedback, role, type, level, createdAt } = interview;
        const date = dayjs(createdAt).format("MMMM D, YYYY");
        const color = scoreColor(feedback.totalScore);

        const categoryRows = (feedback.categoryScores ?? []).map((cat: any) => `
            <tr>
                <td style="padding:10px 12px;border-bottom:1px solid #2a2a4a;color:#ccc;">${cat.name}</td>
                <td style="padding:10px 12px;border-bottom:1px solid #2a2a4a;text-align:center;color:${scoreColor(cat.score)};font-weight:600;">${cat.score}%</td>
                <td style="padding:10px 12px;border-bottom:1px solid #2a2a4a;color:#999;font-size:13px;">${cat.comment ?? ""}</td>
            </tr>`).join("");

        const strengthsList = (feedback.strengths ?? []).map((s: string) => `<li style="margin-bottom:6px;color:#ccc;">${s}</li>`).join("");
        const improvList = (feedback.areasForImprovement ?? []).map((s: string) => `<li style="margin-bottom:6px;color:#ccc;">${s}</li>`).join("");

        const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<title>Intvu Report — ${role}</title>
<style>
*{box-sizing:border-box;margin:0;padding:0}
body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;background:#0f0f23;color:#e2e8f0;padding:40px 24px}
.container{max-width:800px;margin:0 auto}
.header{background:linear-gradient(135deg,#1a1a2e,#16213e);border:1px solid #2a2a4a;border-radius:16px;padding:32px;margin-bottom:24px;text-align:center}
.logo{font-size:28px;font-weight:800;color:#6c63ff}.logo span{color:#43d9ad}
.title{font-size:22px;font-weight:600;color:#fff;margin-top:12px}
.meta{color:#888;font-size:14px;margin-top:6px}
.score-circle{width:100px;height:100px;border-radius:50%;border:4px solid ${color};display:flex;flex-direction:column;align-items:center;justify-content:center;margin:20px auto 0}
.score-num{font-size:28px;font-weight:800;color:${color}}
.score-label{font-size:11px;color:#888;margin-top:2px}
.card{background:#1a1a2e;border:1px solid #2a2a4a;border-radius:12px;padding:24px;margin-bottom:20px}
.card-title{font-size:16px;font-weight:600;color:#fff;margin-bottom:16px}
table{width:100%;border-collapse:collapse}
th{padding:10px 12px;text-align:left;font-size:12px;color:#666;text-transform:uppercase;letter-spacing:0.5px;border-bottom:1px solid #2a2a4a}
ul{list-style:none;padding:0}
ul li::before{content:"→ ";color:#6c63ff}
.assessment{color:#ccc;line-height:1.7;font-size:14px;padding:16px;background:#0f0f23;border-radius:8px}
.footer{text-align:center;color:#444;font-size:12px;margin-top:32px}
.badge{display:inline-block;padding:4px 12px;border-radius:20px;font-size:12px;font-weight:600;margin:4px;background:#6c63ff22;color:#a89cff;border:1px solid #6c63ff44}
</style>
</head>
<body>
<div class="container">
<div class="header">
  <div class="logo">Int<span>vu</span></div>
  <div class="title">Interview Performance Report</div>
  <div class="meta">${userName ?? "Candidate"} · ${date}</div>
  <div style="margin-top:12px">
    <span class="badge">${role}</span>
    <span class="badge">${type}</span>
    ${level ? `<span class="badge">${level}</span>` : ""}
  </div>
  <div class="score-circle">
    <div class="score-num">${feedback.totalScore}%</div>
    <div class="score-label">${scoreLabel(feedback.totalScore)}</div>
  </div>
</div>
${categoryRows ? `<div class="card"><div class="card-title">📊 Category Breakdown</div><table><thead><tr><th>Category</th><th style="text-align:center">Score</th><th>Comment</th></tr></thead><tbody>${categoryRows}</tbody></table></div>` : ""}
${strengthsList ? `<div class="card"><div class="card-title">✅ Strengths</div><ul>${strengthsList}</ul></div>` : ""}
${improvList ? `<div class="card"><div class="card-title">🎯 Areas for Improvement</div><ul>${improvList}</ul></div>` : ""}
${feedback.finalAssessment ? `<div class="card"><div class="card-title">💡 Final Assessment</div><div class="assessment">${feedback.finalAssessment}</div></div>` : ""}
<div class="footer">Generated by Intvu AI · ${date}</div>
</div>
</body>
</html>`;

        return new NextResponse(html, {
            headers: {
                "Content-Type": "text/html",
                "Content-Disposition": `attachment; filename="intvu-report.html"`,
            },
        });
    } catch (error) {
        console.error("Export error:", error);
        return NextResponse.json({ error: "Export failed" }, { status: 500 });
    }
}
