import { NextRequest, NextResponse } from "next/server";
import { google } from "@ai-sdk/google";
import { generateText } from "ai";

function shuffle(arr: string[]) {
    return [...arr].sort(() => Math.random() - 0.5);
}

// Questions organized by ROLE → TYPE → LEVEL
const ALL_QUESTIONS: Record<string, Record<string, Record<string, string[]>>> = {
    "Frontend Developer": {
        Technical: {
            Junior: [
                "What is the difference between HTML, CSS, and JavaScript?",
                "Explain the CSS box model with an example.",
                "What is the difference between let, const, and var in JavaScript?",
                "What are React props and state? How are they different?",
                "Explain what a React component is and how to create one.",
                "What is the difference between == and === in JavaScript?",
                "What is flexbox? How do you center a div?",
                "What is the DOM? How do you select elements using JavaScript?",
                "What is an API? How do you fetch data using fetch()?",
                "What is the difference between margin and padding in CSS?",
                "What is a promise in JavaScript?",
                "What is responsive design and why is it important?",
            ],
            "Mid-level": [
                "Explain React's useEffect hook — when and how do you use it?",
                "What is the difference between useCallback and useMemo?",
                "How does JavaScript's event loop work?",
                "What is CSS specificity and how do you resolve conflicts?",
                "Explain the difference between CSS Grid and Flexbox.",
                "What is lazy loading and how do you implement it in React?",
                "How do you handle forms in React? Controlled vs uncontrolled components?",
                "What is the difference between localStorage and sessionStorage?",
                "Explain React Context API and when to use it.",
                "What is code splitting and how does it improve performance?",
                "How do you handle errors in React using Error Boundaries?",
                "What is debouncing and throttling? Give examples.",
            ],
            Senior: [
                "Explain React's reconciliation algorithm and fiber architecture.",
                "How do you architect a large-scale React application for performance?",
                "What are React Server Components? How do they differ from Client Components?",
                "Explain micro-frontend architecture — when would you use it?",
                "How do you implement and optimize a design system at scale?",
                "What is hydration in Next.js and how do you handle hydration errors?",
                "How do you optimize Core Web Vitals (LCP, FID, CLS)?",
                "Explain advanced state management patterns beyond Redux.",
                "How do you handle real-time features in a React application?",
                "What is your approach to frontend security (XSS, CSRF)?",
                "How do you implement internationalization (i18n) at scale?",
                "Explain Web Workers and how they improve performance.",
            ],
        },
        Behavioral: {
            Junior: [
                "Tell me about a project you built that you are proud of.",
                "How do you approach learning a new technology or framework?",
                "Describe a time you got stuck on a bug — how did you solve it?",
                "How do you handle feedback on your code during reviews?",
                "Tell me about a time you worked in a team on a project.",
            ],
            "Mid-level": [
                "Tell me about a time you significantly improved page performance.",
                "Describe a challenging UI problem you solved creatively.",
                "How do you handle cross-browser compatibility issues?",
                "Tell me about a time you refactored messy frontend code.",
                "How do you collaborate with designers to implement pixel-perfect UIs?",
                "Describe a time you had to deliver a complex feature under deadline.",
            ],
            Senior: [
                "Tell me about a time you led a major frontend architecture decision.",
                "How do you mentor junior developers on frontend best practices?",
                "Describe a time you drove adoption of a new frontend technology.",
                "How do you handle technical disagreements with your team?",
                "Tell me about a time you improved developer experience significantly.",
                "How do you balance technical excellence with business deadlines?",
            ],
        },
        Mixed: {
            Junior: [
                "Tell me about yourself and your frontend projects.",
                "What frontend technologies are you learning right now?",
                "Describe a simple project you built from scratch.",
                "How do you debug a CSS layout issue?",
                "What resources do you use to learn frontend development?",
            ],
            "Mid-level": [
                "Walk me through your most complex frontend project.",
                "How do you approach responsive and mobile-first design?",
                "Tell me about a performance optimization you made.",
                "How do you ensure accessibility in your projects?",
                "What is your code review process?",
            ],
            Senior: [
                "How do you make architectural decisions for large frontend systems?",
                "Tell me about a time you improved team productivity significantly.",
                "How do you balance innovation with stability in frontend development?",
                "Describe your approach to frontend monitoring and observability.",
                "How do you handle legacy frontend codebases?",
            ],
        },
    },
    "Machine Learning Engineer": {
        Technical: {
            Junior: [
                "What is the difference between supervised and unsupervised learning?",
                "Explain what a neural network is in simple terms.",
                "What is overfitting? How do you detect it?",
                "What is the difference between classification and regression?",
                "What is train/validation/test split and why is it important?",
                "Explain what a loss function is and give 2 examples.",
                "What is gradient descent in simple terms?",
                "What is the difference between precision and recall?",
                "What is feature scaling and why is it needed?",
                "Explain what a confusion matrix is.",
                "What is cross-validation and why do we use it?",
                "What is the difference between a parameter and a hyperparameter?",
            ],
            "Mid-level": [
                "Explain backpropagation step by step in a neural network.",
                "What is the difference between L1 and L2 regularization?",
                "How would you handle class imbalance in a binary classification problem?",
                "Explain the difference between batch gradient descent and mini-batch.",
                "What is the vanishing gradient problem and how do you solve it?",
                "Explain dropout and how it prevents overfitting.",
                "What is the difference between bagging and boosting?",
                "How do you evaluate an ML model beyond accuracy?",
                "Explain the difference between Random Forest and XGBoost.",
                "What is transfer learning and when would you use it?",
                "How do you select the right features for a model?",
                "What is the curse of dimensionality?",
            ],
            Senior: [
                "Explain the transformer architecture and self-attention mechanism in detail.",
                "How do you deploy and monitor ML models in production at scale?",
                "What is MLOps? Design a complete ML pipeline.",
                "How do you handle concept drift in production ML models?",
                "Explain the difference between BERT, GPT, and T5 architectures.",
                "How do you design a recommendation system for millions of users?",
                "What is federated learning and when would you use it?",
                "How do you optimize model inference latency for real-time serving?",
                "Explain reinforcement learning from human feedback (RLHF).",
                "How do you approach responsible AI and model fairness?",
                "What is quantization and how does it affect model performance?",
                "How do you handle distributed training for large models?",
            ],
        },
        Behavioral: {
            Junior: [
                "Tell me about an ML project you built — what did you learn?",
                "How do you approach learning new ML papers and techniques?",
                "Describe a time you struggled with a dataset — how did you solve it?",
                "How do you handle it when your model doesn't perform as expected?",
                "Tell me about your experience with ML frameworks (PyTorch, TensorFlow).",
            ],
            "Mid-level": [
                "Describe an ML project you built from scratch to production.",
                "Tell me about a time your model failed in production — what happened?",
                "How do you explain ML results to non-technical stakeholders?",
                "Describe a time you had to choose between accuracy and interpretability.",
                "Tell me about a time you significantly improved model performance.",
                "How do you collaborate with data engineers and product teams?",
            ],
            Senior: [
                "Tell me about the most complex ML system you have architected.",
                "How do you build and mentor ML teams?",
                "Describe a time you led adoption of a new ML approach in your organization.",
                "How do you handle disagreements about ML methodology with stakeholders?",
                "Tell me about a time you solved a critical production ML failure.",
                "How do you balance research innovation with production reliability?",
            ],
        },
        Mixed: {
            Junior: [
                "Tell me about yourself and your ML background.",
                "What ML projects have you worked on?",
                "How do you stay updated with ML research?",
                "What is your experience with Python for ML?",
                "Tell me about a dataset you worked with.",
            ],
            "Mid-level": [
                "Walk me through your most impactful ML project.",
                "How do you decide which algorithm to use for a problem?",
                "What is your ML experimentation process?",
                "How do you handle collaboration between ML and engineering teams?",
                "What tools do you use for experiment tracking?",
            ],
            Senior: [
                "How do you approach building ML platforms and infrastructure?",
                "Tell me about a time you drove ML adoption at an organizational level.",
                "How do you evaluate build vs buy for ML tooling?",
                "What is your approach to ML research vs applied ML?",
                "How do you ensure ML models are ethical and unbiased?",
            ],
        },
    },
    "Backend Developer": {
        Technical: {
            Junior: [
                "What is the difference between GET and POST HTTP methods?",
                "What is a REST API? Explain its principles.",
                "What is the difference between SQL and NoSQL databases?",
                "What is a primary key and foreign key in a database?",
                "Explain what CRUD operations are.",
                "What is JSON and how is it used in APIs?",
                "What is authentication vs authorization?",
                "What is a 404 vs 500 HTTP status code?",
                "What is a database index and why is it used?",
                "Explain what middleware is in a backend framework.",
                "What is an environment variable and why do we use them?",
                "What is the difference between synchronous and asynchronous code?",
            ],
            "Mid-level": [
                "Explain the difference between REST and GraphQL APIs.",
                "How does database indexing work? When do you use composite indexes?",
                "What is connection pooling and why is it important?",
                "Explain JWT tokens — how do they work and what are their security risks?",
                "What is the N+1 query problem and how do you solve it?",
                "How do you implement pagination efficiently for large datasets?",
                "What is database normalization? When do you denormalize?",
                "Explain different caching strategies: write-through, write-back, cache-aside.",
                "What is the difference between optimistic and pessimistic locking?",
                "How do you handle database migrations in production?",
                "What is rate limiting and how do you implement it?",
                "Explain message queues — when would you use Kafka vs RabbitMQ?",
            ],
            Senior: [
                "Explain the CAP theorem and how it influences system design decisions.",
                "How do you design a system to handle 10 million concurrent users?",
                "What is database sharding? How do you choose a sharding key?",
                "Explain event sourcing and CQRS patterns.",
                "How do you design a distributed transaction system (saga pattern)?",
                "What is a service mesh and when would you use it?",
                "How do you design for high availability (99.99% uptime)?",
                "Explain consistent hashing and how it's used in distributed systems.",
                "How do you approach database query optimization at scale?",
                "What is the circuit breaker pattern and how do you implement it?",
                "How do you handle data consistency across microservices?",
                "Design a real-time notification system for millions of users.",
            ],
        },
        Behavioral: {
            Junior: [
                "Tell me about a backend project you built.",
                "How do you approach debugging a server error?",
                "Tell me about a time you learned a new backend technology quickly.",
                "How do you handle it when you don't know the answer to a problem?",
                "Describe your experience working with databases.",
            ],
            "Mid-level": [
                "Tell me about a time you improved API performance significantly.",
                "Describe a production incident you handled — how did you resolve it?",
                "How do you handle technical debt in backend systems?",
                "Tell me about a complex database design decision you made.",
                "How do you ensure API security in your projects?",
                "Describe a time you had to refactor legacy backend code.",
            ],
            Senior: [
                "Tell me about the most complex backend system you have designed.",
                "How do you lead incident response for critical production failures?",
                "Describe a time you drove a major backend architecture change.",
                "How do you mentor backend engineers on system design?",
                "Tell me about a time you improved system reliability significantly.",
                "How do you make build vs buy decisions for backend infrastructure?",
            ],
        },
        Mixed: {
            Junior: [
                "Tell me about yourself and your backend experience.",
                "What backend languages and frameworks have you used?",
                "Describe a simple API you built.",
                "How do you learn new backend technologies?",
                "What databases have you worked with?",
            ],
            "Mid-level": [
                "Walk me through your most complex backend project.",
                "How do you approach API design and documentation?",
                "What is your approach to testing backend systems?",
                "How do you handle logging and monitoring in your applications?",
                "What is your experience with cloud services?",
            ],
            Senior: [
                "How do you approach designing scalable backend architectures?",
                "Tell me about a time you solved a major scalability challenge.",
                "How do you evaluate new backend technologies for adoption?",
                "What is your approach to backend security at scale?",
                "How do you handle organizational alignment on backend standards?",
            ],
        },
    },
    "Data Scientist": {
        Technical: {
            Junior: [
                "What is the difference between mean, median, and mode?",
                "Explain what a p-value means in simple terms.",
                "What is the difference between supervised and unsupervised learning?",
                "What is linear regression? How does it work?",
                "What is a histogram and what does it tell you about data?",
                "What is the difference between correlation and causation?",
                "What is data cleaning and why is it important?",
                "What is a normal distribution? Why is it important?",
                "What is overfitting in machine learning?",
                "Explain what train/test split is and why we need it.",
                "What tools do you use for data analysis? (Python, pandas, etc.)",
                "What is feature engineering?",
            ],
            "Mid-level": [
                "Explain A/B testing — how do you determine statistical significance?",
                "What is the bias-variance tradeoff? How do you balance it?",
                "Explain PCA — what does it do and when would you use it?",
                "What is cross-validation and why is k-fold CV important?",
                "How do you handle missing data in a real dataset?",
                "Explain the difference between precision, recall, and F1 score.",
                "What is Random Forest? How does it reduce overfitting?",
                "Explain gradient boosting — how does XGBoost differ from Random Forest?",
                "How do you detect and handle outliers in data?",
                "What is the difference between parametric and non-parametric tests?",
                "Explain time series analysis — what is stationarity?",
                "How do you handle class imbalance in classification?",
            ],
            Senior: [
                "How do you design an experimentation platform for A/B testing at scale?",
                "Explain causal inference — difference between observational and experimental data.",
                "How do you build and deploy ML models in a production data science workflow?",
                "What is Bayesian vs frequentist statistics? When do you use each?",
                "How do you measure the business impact of a data science project?",
                "Explain multi-armed bandit algorithms vs A/B testing.",
                "How do you handle data drift and model degradation over time?",
                "What is your approach to building data pipelines for ML?",
                "How do you communicate statistical uncertainty to business stakeholders?",
                "Explain survival analysis and when you would use it.",
                "How do you approach building recommendation systems?",
                "What is your experience with big data tools (Spark, Hadoop)?",
            ],
        },
        Behavioral: {
            Junior: [
                "Tell me about a data analysis project you worked on.",
                "How do you approach a dataset you have never seen before?",
                "Describe a time you found an interesting pattern in data.",
                "How do you handle it when your analysis doesn't give clear results?",
                "What data science tools and libraries are you learning?",
            ],
            "Mid-level": [
                "Describe a data analysis that directly influenced a business decision.",
                "Tell me about a time your analysis revealed an unexpected insight.",
                "How do you communicate statistical findings to non-technical people?",
                "Describe a time you had to clean a very messy dataset.",
                "Tell me about a time your model or analysis was wrong.",
                "How do you handle stakeholders who want to misinterpret data?",
            ],
            Senior: [
                "Tell me about a data science initiative you led end-to-end.",
                "How do you build a data-driven culture in an organization?",
                "Describe a time you influenced major business strategy with data.",
                "How do you handle ethical concerns in data science projects?",
                "Tell me about a time you scaled a data science team.",
                "How do you balance statistical rigor with business speed?",
            ],
        },
        Mixed: {
            Junior: [
                "Tell me about yourself and your data science background.",
                "What data science projects have you worked on?",
                "What programming languages do you use for data analysis?",
                "How do you approach learning new data science techniques?",
                "Tell me about a visualization you created.",
            ],
            "Mid-level": [
                "Walk me through a complete data science project end-to-end.",
                "How do you decide which model to use for a problem?",
                "What is your approach to exploratory data analysis?",
                "How do you validate and present your findings?",
                "What tools do you use for ML experimentation?",
            ],
            Senior: [
                "How do you prioritize data science projects for maximum business impact?",
                "Tell me about building a data science practice from the ground up.",
                "How do you ensure data quality across your organization?",
                "What is your approach to responsible and ethical AI?",
                "How do you align data science goals with business objectives?",
            ],
        },
    },
    "DevOps Engineer": {
        Technical: {
            Junior: [
                "What is the difference between a container and a virtual machine?",
                "What is Docker? What problem does it solve?",
                "Explain what CI/CD means in simple terms.",
                "What is version control? How does Git work?",
                "What is SSH and how do you use it?",
                "What is a load balancer and why is it used?",
                "What is the difference between TCP and UDP?",
                "What is DNS and how does it work?",
                "What is a firewall and what does it do?",
                "What is Linux and why is it important for DevOps?",
                "What is a cron job?",
                "What is the difference between HTTP and HTTPS?",
            ],
            "Mid-level": [
                "How does Kubernetes work? Explain pods, services, and deployments.",
                "What is infrastructure as code? Compare Terraform vs Ansible.",
                "How do you design a CI/CD pipeline for a production application?",
                "Explain blue-green vs canary vs rolling deployments.",
                "What is Docker Compose and when do you use it vs Kubernetes?",
                "How do you implement monitoring and alerting for microservices?",
                "What is a reverse proxy? How does Nginx work?",
                "Explain how you would set up auto-scaling in AWS.",
                "What is container networking? Explain overlay networks.",
                "How do you handle secrets management in a DevOps environment?",
                "What is log aggregation? How do you use the ELK stack?",
                "How do you handle zero-downtime deployments?",
            ],
            Senior: [
                "How do you architect a multi-cloud or hybrid cloud infrastructure?",
                "What is GitOps? How do ArgoCD and Flux work?",
                "How do you design a disaster recovery strategy with RTO/RPO targets?",
                "Explain Kubernetes operators — how do you build custom controllers?",
                "How do you implement a service mesh with Istio at scale?",
                "What is FinOps? How do you optimize cloud costs at scale?",
                "How do you design a zero-trust network security architecture?",
                "Explain distributed tracing — how do you implement it across microservices?",
                "How do you handle Kubernetes cluster upgrades without downtime?",
                "What is chaos engineering? How do you implement it safely?",
                "How do you design a platform engineering team and internal developer platform?",
                "Explain compliance automation (SOC2, ISO27001) in infrastructure.",
            ],
        },
        Behavioral: {
            Junior: [
                "Tell me about a time you automated a manual task.",
                "How do you approach learning a new DevOps tool or technology?",
                "Describe a time you fixed a deployment issue.",
                "How do you handle working with developers who don't follow processes?",
                "Tell me about your experience with cloud platforms.",
            ],
            "Mid-level": [
                "Tell me about a major production outage you handled.",
                "Describe how you improved deployment frequency at a company.",
                "Tell me about a time you automated a complex manual process.",
                "How do you handle on-call rotations and incident response?",
                "Describe a time you improved infrastructure security.",
                "Tell me about a time you reduced infrastructure costs.",
            ],
            Senior: [
                "Tell me about designing and scaling a DevOps organization.",
                "How do you drive DevOps culture adoption across engineering teams?",
                "Describe a critical infrastructure failure you led recovery from.",
                "How do you handle security incidents at an organizational level?",
                "Tell me about building a platform engineering team from scratch.",
                "How do you balance stability with innovation in infrastructure?",
            ],
        },
        Mixed: {
            Junior: [
                "Tell me about yourself and your DevOps experience.",
                "What DevOps tools have you worked with?",
                "Describe a simple pipeline you built.",
                "How do you approach learning new cloud technologies?",
                "What is your experience with Linux?",
            ],
            "Mid-level": [
                "Walk me through your most complex infrastructure setup.",
                "How do you approach cloud cost optimization?",
                "Tell me about improving system reliability.",
                "What is your approach to DevSecOps?",
                "How do you handle configuration management?",
            ],
            Senior: [
                "How do you build a DevOps strategy for an organization?",
                "Tell me about driving major infrastructure transformation.",
                "How do you evaluate new DevOps tooling and platforms?",
                "What is your approach to platform engineering?",
                "How do you align DevOps initiatives with business goals?",
            ],
        },
    },
    "UI/UX Designer": {
        Technical: {
            Junior: [
                "What is the difference between UX and UI design?",
                "What is a wireframe? How is it different from a prototype?",
                "What design tools have you used? (Figma, Adobe XD, Sketch)",
                "What is a user persona and how do you create one?",
                "What is a user journey map?",
                "What is the difference between a mockup and a prototype?",
                "What are the basic principles of visual design (color, typography, space)?",
                "What is a style guide and why is it important?",
                "What does accessibility mean in design?",
                "What is a heuristic evaluation?",
                "What is the F-pattern in web design?",
                "What is white space and why is it important?",
            ],
            "Mid-level": [
                "Explain design thinking — walk me through the 5 stages.",
                "How do you conduct user research? What methods do you use?",
                "What is a design system and how do you build one?",
                "How do you measure the success of a UX design?",
                "Explain the Gestalt principles and how you apply them.",
                "What is usability testing? How do you plan a test session?",
                "How do you design for mobile-first?",
                "What is information architecture? How do you design navigation?",
                "Explain WCAG accessibility guidelines — what are the levels?",
                "What is interaction design? Give examples of micro-interactions.",
                "How do you approach designing for different user mental models?",
                "What is A/B testing in UX design?",
            ],
            Senior: [
                "How do you build and scale a design system across multiple products?",
                "What is your approach to strategic UX research at an organizational level?",
                "How do you measure design's ROI and business impact?",
                "Explain service design — how does it differ from product design?",
                "How do you design for complex enterprise applications?",
                "What is your approach to designing for emerging platforms (AR/VR, voice)?",
                "How do you align design strategy with business objectives?",
                "What is jobs-to-be-done (JTBD) framework in UX?",
                "How do you handle designing for global, cross-cultural audiences?",
                "Explain design operations (DesignOps) — how do you scale design teams?",
                "How do you integrate quantitative data into UX decision making?",
                "What is your approach to ethical design and dark patterns?",
            ],
        },
        Behavioral: {
            Junior: [
                "Tell me about a design project you are most proud of.",
                "How do you handle feedback on your designs?",
                "Describe a time you had to redesign something that wasn't working.",
                "How do you approach learning new design tools?",
                "Tell me about a time you collaborated with a developer.",
            ],
            "Mid-level": [
                "Tell me about a design that significantly improved user engagement.",
                "Describe a time user research completely changed your design direction.",
                "How do you handle feedback from developers who say your design is too complex?",
                "Tell me about a time you advocated for the user against business pressure.",
                "Describe your process when you receive conflicting stakeholder feedback.",
                "Tell me about a design failure and what you learned.",
            ],
            Senior: [
                "Tell me about leading a major design system implementation.",
                "How do you build and grow a design team?",
                "Describe a time you drove UX strategy at an organizational level.",
                "How do you handle design disagreements with product and engineering leadership?",
                "Tell me about building a user research practice from scratch.",
                "How do you demonstrate design value to business stakeholders?",
            ],
        },
        Mixed: {
            Junior: [
                "Tell me about yourself and your design background.",
                "What design projects have you worked on?",
                "How do you approach a new design project?",
                "What design tools are you most comfortable with?",
                "Tell me about your design process.",
            ],
            "Mid-level": [
                "Walk me through your design process from research to delivery.",
                "How do you balance aesthetics with usability?",
                "Tell me about a time you improved conversion through design.",
                "How do you collaborate with developers to ensure faithful implementation?",
                "How do you stay updated with UI/UX trends?",
            ],
            Senior: [
                "How do you approach building a design culture in an organization?",
                "Tell me about scaling design across multiple product teams.",
                "How do you make strategic design decisions with limited user data?",
                "What is your approach to design leadership and mentorship?",
                "How do you integrate design thinking into product strategy?",
            ],
        },
    },
    "Product Manager": {
        Technical: {
            Junior: [
                "What is a product roadmap and what does it contain?",
                "What is the difference between a feature and a user story?",
                "What are KPIs? Give 3 examples for a mobile app.",
                "What is agile development? What is a sprint?",
                "What is the difference between a product vision and a product strategy?",
                "What is a PRD (Product Requirements Document)?",
                "What is MVP (Minimum Viable Product)?",
                "What are user personas and why do they matter?",
                "What is the MoSCoW prioritization framework?",
                "What is a stakeholder? How do you manage stakeholder expectations?",
                "What is product-market fit?",
                "What is the difference between a bug and a feature request?",
            ],
            "Mid-level": [
                "How do you prioritize features using RICE or Kano model?",
                "Explain OKRs — how do you write good OKRs?",
                "How do you conduct user research and synthesize findings?",
                "What is A/B testing? How do you design a product experiment?",
                "How do you measure the success of a product launch?",
                "Explain the product development lifecycle from idea to launch.",
                "How do you handle competing priorities from multiple stakeholders?",
                "What is net promoter score (NPS) and how do you use it?",
                "How do you write effective user stories and acceptance criteria?",
                "What is the difference between output and outcome metrics?",
                "How do you approach competitive analysis?",
                "What is user story mapping and how do you use it?",
            ],
            Senior: [
                "How do you build and communicate a 3-year product vision?",
                "Explain product-led growth (PLG) strategy — how do you implement it?",
                "How do you build a data-driven product culture?",
                "What is platform strategy? How do you think about ecosystem products?",
                "How do you approach pricing strategy for a SaaS product?",
                "What is your framework for making major product bets?",
                "How do you align product strategy with company business goals?",
                "Explain the build vs buy vs partner decision framework.",
                "How do you manage a product portfolio across multiple segments?",
                "What is your approach to international product expansion?",
                "How do you handle a major product pivot?",
                "What is your approach to product analytics infrastructure?",
            ],
        },
        Behavioral: {
            Junior: [
                "Tell me about a product or feature idea you had — how did you think about it?",
                "How do you approach understanding user needs?",
                "Describe a time you had to prioritize between two features.",
                "How do you handle it when you disagree with a developer's estimate?",
                "Tell me about a product you love and why.",
            ],
            "Mid-level": [
                "Tell me about a product feature you championed from idea to launch.",
                "Describe a time you had to say no to a stakeholder's request.",
                "How do you handle conflicts between engineering and business teams?",
                "Tell me about a product decision that failed — what did you learn?",
                "Describe a time you used data to change product direction.",
                "How do you build consensus across cross-functional teams?",
            ],
            Senior: [
                "Tell me about a major product strategy you defined and executed.",
                "How do you build alignment across C-suite on product vision?",
                "Describe a time you led a product through a major pivot.",
                "How do you build high-performing product teams?",
                "Tell me about a time you drove significant business impact through product.",
                "How do you handle organizational conflict over product direction?",
            ],
        },
        Mixed: {
            Junior: [
                "Tell me about yourself and why you want to be a PM.",
                "What product do you use every day and how would you improve it?",
                "How do you think about user problems?",
                "What metrics would you track for a food delivery app?",
                "How do you approach learning about a new market?",
            ],
            "Mid-level": [
                "How would you prioritize the roadmap for a new product?",
                "Walk me through how you would launch a major new feature.",
                "How do you balance short-term wins with long-term vision?",
                "Tell me about managing relationships with engineering leads.",
                "What is your approach to user research and discovery?",
            ],
            Senior: [
                "How do you set product strategy for a business unit?",
                "Tell me about building a product organization from scratch.",
                "How do you measure and communicate product success to the board?",
                "What is your approach to building product culture?",
                "How do you handle major market disruptions to your product?",
            ],
        },
    },
    "Software Architect": {
        Technical: {
            Junior: [
                "What is the difference between a library and a framework?",
                "What are design patterns? Give 3 examples.",
                "What is the difference between coupling and cohesion?",
                "What is the Single Responsibility Principle?",
                "What is the difference between SQL and NoSQL databases?",
                "What is a REST API? What makes a good API design?",
                "What is version control and why is it important for architecture?",
                "What is the difference between horizontal and vertical scaling?",
                "What is a microservice?",
                "What is a message queue?",
                "What is caching and why is it important?",
                "What is load balancing?",
            ],
            "Mid-level": [
                "Explain the SOLID principles with real examples.",
                "What is the difference between monolithic and microservices architecture?",
                "Explain common design patterns: Factory, Observer, Strategy, Decorator.",
                "How do you design a RESTful API that is scalable and maintainable?",
                "What is event-driven architecture? Explain publish-subscribe pattern.",
                "How does database indexing affect system architecture decisions?",
                "What is the API gateway pattern in microservices?",
                "Explain the difference between synchronous and asynchronous communication.",
                "What is a distributed system? What challenges does it introduce?",
                "How do you approach technical debt in a growing system?",
                "What is the strangler fig pattern for legacy migration?",
                "Explain the difference between orchestration and choreography in microservices.",
            ],
            Senior: [
                "Design a system like Twitter that handles 500 million daily active users.",
                "Explain event sourcing and CQRS — when and why would you use them?",
                "How do you design for 99.999% availability in a distributed system?",
                "What is the CAP theorem and how does it influence your architecture?",
                "Explain the saga pattern for distributed transactions.",
                "How do you approach domain-driven design (DDD) for complex domains?",
                "What is a service mesh? When does the complexity justify using one?",
                "How do you design a globally distributed database system?",
                "Explain consistent hashing — how is it used in distributed systems?",
                "What is chaos engineering and how does it improve architecture?",
                "How do you architect a zero-downtime database migration at scale?",
                "Explain the cell-based architecture pattern for large-scale systems.",
            ],
        },
        Behavioral: {
            Junior: [
                "Tell me about a system design decision you made and why.",
                "How do you approach learning about new architectural patterns?",
                "Describe a time you identified a technical problem before it became critical.",
                "How do you handle it when you realize your technical decision was wrong?",
                "Tell me about a technical challenge you solved creatively.",
            ],
            "Mid-level": [
                "Tell me about the most complex system you have designed.",
                "How do you get buy-in from teams for architectural changes?",
                "Describe a time you had to migrate a legacy system.",
                "How do you handle technical disagreements with senior engineers?",
                "Tell me about an architectural decision you later regretted.",
                "How do you handle technical debt at a system level?",
            ],
            Senior: [
                "Tell me about an architecture you designed that scaled to millions of users.",
                "How do you build organizational alignment on technical architecture?",
                "Describe leading a major platform migration with zero downtime.",
                "How do you mentor engineers on architectural thinking?",
                "Tell me about making a critical build vs buy decision.",
                "How do you balance architectural purity with business constraints?",
            ],
        },
        Mixed: {
            Junior: [
                "Tell me about yourself and your interest in software architecture.",
                "What systems or codebases have you worked on?",
                "How do you approach understanding a new codebase?",
                "What engineering principles are most important to you?",
                "Tell me about a technical decision you are proud of.",
            ],
            "Mid-level": [
                "Walk me through the architecture of a system you designed.",
                "How do you make major technical decisions?",
                "What is your approach to system documentation?",
                "How do you evaluate new technologies for adoption?",
                "Tell me about improving an existing system's architecture.",
            ],
            Senior: [
                "How do you define technical strategy for an engineering organization?",
                "Tell me about building a culture of good architecture.",
                "How do you handle legacy systems at an organizational level?",
                "What is your approach to architecture governance?",
                "How do you align technical architecture with business strategy?",
            ],
        },
    },
    "QA Engineer": {
        Technical: {
            Junior: [
                "What is the difference between manual and automated testing?",
                "What is a test case? What should it include?",
                "What is the difference between functional and non-functional testing?",
                "What is a bug report? What information should it contain?",
                "What is regression testing?",
                "What is the difference between black-box and white-box testing?",
                "What is the testing pyramid?",
                "What is smoke testing vs sanity testing?",
                "What is the difference between a bug, defect, and failure?",
                "What is user acceptance testing (UAT)?",
                "What is cross-browser testing?",
                "What is a test plan?",
            ],
            "Mid-level": [
                "Explain the testing pyramid — unit, integration, and end-to-end tests.",
                "What is TDD vs BDD? How do they differ in practice?",
                "How do you design a test strategy for a new feature?",
                "What is API testing? How do you test RESTful APIs with tools like Postman?",
                "How do you approach performance and load testing?",
                "What is continuous testing in a CI/CD pipeline?",
                "Explain test coverage — what metrics do you use?",
                "What is exploratory testing and when do you use it?",
                "How do you handle flaky tests in automation suites?",
                "What is mutation testing?",
                "How do you test for security vulnerabilities (OWASP Top 10)?",
                "How do you approach mobile testing vs web testing?",
            ],
            Senior: [
                "How do you build a test automation framework from scratch?",
                "What is your approach to testing microservices architectures?",
                "How do you implement shift-left testing in an organization?",
                "Explain chaos engineering from a QA perspective.",
                "How do you measure and improve overall software quality at an org level?",
                "What is contract testing? How do you implement Pact testing?",
                "How do you approach performance engineering vs performance testing?",
                "What is your strategy for testing AI/ML systems?",
                "How do you build a quality culture across engineering teams?",
                "Explain observability vs monitoring from a QA perspective.",
                "How do you handle test data management at scale?",
                "What is your approach to accessibility testing?",
            ],
        },
        Behavioral: {
            Junior: [
                "Tell me about a bug you found that was hard to reproduce.",
                "How do you prioritize which features to test first?",
                "Describe a time you had to learn a new testing tool quickly.",
                "How do you handle pressure to skip testing to meet deadlines?",
                "Tell me about your experience with test automation.",
            ],
            "Mid-level": [
                "Tell me about a critical bug you found that prevented a production issue.",
                "Describe a time you pushed back on releasing due to quality concerns.",
                "Tell me about a time you improved the testing process significantly.",
                "Describe a time a bug made it to production — how did you handle it?",
                "How do you collaborate with developers to ensure testability?",
                "Tell me about building a test automation suite from scratch.",
            ],
            Senior: [
                "Tell me about implementing a quality strategy across an organization.",
                "How do you build a QA team and define quality standards?",
                "Describe a time you drove a major improvement in release quality.",
                "How do you handle executive pressure to release with known quality issues?",
                "Tell me about measuring and reporting on software quality to leadership.",
                "How do you build a culture of quality in engineering teams?",
            ],
        },
        Mixed: {
            Junior: [
                "Tell me about yourself and your QA background.",
                "What testing tools have you used?",
                "How do you approach testing a new feature?",
                "Tell me about a bug you are proud of finding.",
                "How do you stay organized when testing multiple features?",
            ],
            "Mid-level": [
                "Walk me through your approach to testing a complete application.",
                "How do you prioritize testing when time is limited?",
                "What test automation frameworks are you experienced with?",
                "How do you report on quality metrics to stakeholders?",
                "Tell me about significantly improving test coverage.",
            ],
            Senior: [
                "How do you define and implement a quality strategy?",
                "Tell me about building a QA practice from the ground up.",
                "How do you align QA goals with business objectives?",
                "What is your approach to quality in agile/DevOps environments?",
                "How do you evaluate and adopt new testing technologies?",
            ],
        },
    },
    "Full Stack Developer": {
        Technical: {
            Junior: [
                "What is the difference between frontend and backend development?",
                "What is a REST API and how do frontend and backend communicate?",
                "What is the difference between GET, POST, PUT, and DELETE requests?",
                "What is a database and how do you connect it to a backend?",
                "What is HTML, CSS, JavaScript and how do they work together?",
                "What is a framework? Give one frontend and one backend example.",
                "What is CORS and why does it happen?",
                "What is an environment variable and why do we use it?",
                "What is the difference between client-side and server-side rendering?",
                "What is authentication? What is the difference between login and signup?",
                "What is version control? How do you use Git?",
                "What is JSON and how is it used between frontend and backend?",
            ],
            "Mid-level": [
                "How do you decide which logic should live on frontend vs backend?",
                "Explain how HTTP cookies and sessions work end-to-end.",
                "What is SSR vs CSR vs static generation in Next.js?",
                "How do you handle authentication in a full stack application with JWT?",
                "Explain WebSockets — when would you use them over REST?",
                "How do you design a file upload system (frontend to backend to storage)?",
                "What is an ORM? Explain pros and cons vs raw SQL.",
                "How do you implement real-time features in a full stack app?",
                "Explain database relationships — one-to-many, many-to-many.",
                "How do you handle form validation on both frontend and backend?",
                "What is your approach to error handling across the full stack?",
                "How do you manage state in a full stack application?",
            ],
            Senior: [
                "How do you architect a full stack application for 1 million users?",
                "Explain micro-frontend architecture — when would you use it?",
                "How do you approach database design for a complex full stack application?",
                "What is your strategy for full stack performance optimization?",
                "How do you implement end-to-end security in a full stack application?",
                "Explain serverless architecture — when is it appropriate for full stack?",
                "How do you handle distributed caching in a full stack system?",
                "What is your approach to full stack observability and monitoring?",
                "How do you design an API for both mobile and web clients?",
                "Explain the BFF (Backend for Frontend) pattern.",
                "How do you handle database migrations in a full stack production system?",
                "What is your approach to full stack testing strategy?",
            ],
        },
        Behavioral: {
            Junior: [
                "Tell me about a full stack project you built.",
                "How do you approach debugging when you don't know if it's a frontend or backend issue?",
                "Describe a time you learned a new technology for a project.",
                "How do you handle working on both frontend and backend simultaneously?",
                "Tell me about a challenge you faced building a full stack application.",
            ],
            "Mid-level": [
                "Tell me about a full stack feature you built entirely on your own.",
                "How do you balance working on both frontend and backend in the same sprint?",
                "Describe a time you debugged an issue spanning frontend and backend.",
                "How do you prioritize technical decisions when you own the full stack?",
                "Tell me about a performance issue you solved across the entire stack.",
                "Describe a time you had to quickly learn a new framework.",
            ],
            Senior: [
                "Tell me about the most complex full stack system you have designed.",
                "How do you lead a full stack engineering team?",
                "Describe a time you drove a major technical migration.",
                "How do you mentor engineers across frontend and backend?",
                "Tell me about making build vs buy decisions for full stack tooling.",
                "How do you handle technical debt across the full stack?",
            ],
        },
        Mixed: {
            Junior: [
                "Tell me about yourself and your full stack experience.",
                "What technologies make up your preferred full stack?",
                "Describe a project you built from scratch.",
                "How do you approach learning full stack development?",
                "What is your experience with databases?",
            ],
            "Mid-level": [
                "Walk me through building a complete feature from database to UI.",
                "What is your preferred full stack technology combination and why?",
                "How do you approach full stack testing?",
                "Tell me about your most complex full stack project.",
                "How do you handle data consistency across the stack?",
            ],
            Senior: [
                "How do you make architectural decisions for full stack systems?",
                "Tell me about scaling a full stack application significantly.",
                "How do you evaluate new full stack technologies for adoption?",
                "What is your approach to full stack security?",
                "How do you handle organizational alignment on full stack standards?",
            ],
        },
    },
};

export async function POST(req: NextRequest) {
    const body = await req.json();
    const { role = "Full Stack Developer", type = "Mixed", level = "Mid-level", count = 5 } = body;

    try {
        const randomSeed = Math.floor(Math.random() * 99999);

        const prompt = `[Seed:${randomSeed}] You are a strict technical interviewer.

Generate EXACTLY ${count} interview questions for:
ROLE: ${role}
LEVEL: ${level}
TYPE: ${type}

${level === "Junior" ? "Questions should test BASIC concepts only. No advanced topics." : ""}
${level === "Mid-level" ? "Questions should test INTERMEDIATE concepts. Real-world implementation experience." : ""}
${level === "Senior" ? "Questions should test ADVANCED concepts. System design, architecture, leadership." : ""}

${type === "Technical" ? `TECHNICAL ONLY — ${role} specific technical knowledge. NO behavioral questions.` : ""}
${type === "Behavioral" ? "BEHAVIORAL ONLY — STAR format. Past experience, teamwork, leadership. NO technical questions." : ""}
${type === "Mixed" ? `MIXED — 50% technical ${role} questions + 50% behavioral.` : ""}

Return ONLY a JSON array of exactly ${count} strings.
["Question 1?", "Question 2?"]`;

        const { text } = await generateText({
            model: google("gemini-1.5-flash"),
            prompt,
        });

        let cleaned = text.replace(/```json/g, "").replace(/```/g, "").trim();
        const start = cleaned.indexOf("[");
        const end = cleaned.lastIndexOf("]");
        if (start !== -1 && end !== -1) cleaned = cleaned.substring(start, end + 1);

        const questions: string[] = JSON.parse(cleaned);
        return NextResponse.json({ questions: questions.slice(0, count) });

    } catch (error) {
        console.error("Gemini failed, using local fallback:", error);

        // Get role-specific, level-specific questions
        const roleData = ALL_QUESTIONS[role] || ALL_QUESTIONS["Full Stack Developer"];
        const typeData = roleData[type] || roleData["Mixed"];
        const levelData = typeData[level] || typeData["Mid-level"];
        const pool = shuffle(levelData);

        return NextResponse.json({ questions: pool.slice(0, count) });
    }
}